OCAMLMAKEFILE = ../../OCamlMakefile
ANNOTATE = yes

SOURCES = p4_orm.ml pa_orm.ml
PACKS = type-conv.syntax weakid.syntax type-of.syntax
RESULT = pa_orm
USE_CAMLP4 = yes

.PHONY: all
all: dcl
	@ :

include $(OCAMLMAKEFILE)
