OCAMLMAKEFILE = ../../OCamlMakefile
ANNOTATE = yes

SOURCES = p4_hash.ml pa_hash.ml p4_utils.ml p4_orm_sqlite.ml p4_orm_appengine.ml pa_orm.ml
PACKS = type-conv dyntype.syntax
RESULT = pa_orm
USE_CAMLP4 = yes

.PHONY: all
all: dcl
	@ :

include $(OCAMLMAKEFILE)
