OCAMLMAKEFILE = ../OCamlMakefile
ANNOTATE = yes

SOURCES = value.ml p4_value.ml ../hash/p4_hash.ml ../weakid/p4_weakid.ml pa_value.ml
PACKS = type-conv
RESULT = pa_value
USE_CAMLP4 = yes

.PHONY: all
all: dcl ncl
	@ :

include $(OCAMLMAKEFILE)
