OCAMLMAKEFILE = OCamlMakefile

ANNOTATE = yes
export ANNOTATE

SOURCES=test_schema.ml
RESULT=test_schema_generate
PACKS=unix
LIBS=sql_orm

.PHONY: all
all: dnc
	./$(RESULT)

include $(OCAMLMAKEFILE)

