OCAMLMAKEFILE = OCamlMakefile

ANNOTATE = yes
export ANNOTATE
DEBUG = yes
export DEBUG

OCAMLRUNPARAM=b
export OCAMLRUNPARAM

SOURCES=sql_access.ml ormtest.ml test.ml
THREADS=yes
RESULT=ormtest
PACKS=unix sqlite3 ounit
LIBDIRS=/opt/local/lib

PP=./camlp4find $(PACKS)
export PP

.PHONY: all
all: dnc
	@ :

include $(OCAMLMAKEFILE)

