OCAMLMAKEFILE = ../OCamlMakefile

ANNOTATE = yes
export ANNOTATE
DEBUG = yes
export DEBUG

OCAMLRUNPARAM=b
export OCAMLRUNPARAM

SOURCES=foreign.mli foreign.ml ormtest.mli ormtest.ml test.ml
THREADS=yes
RESULT=ormtest
PACKS=unix sqlite3 ounit
LIBDIRS=/opt/local/lib
DOC_FILES=ormtest.mli

TRASH=test.db

PP=./camlp4find $(PACKS)
export PP

.PHONY: all
all: dnc htdoc
	@ :

include $(OCAMLMAKEFILE)

