export OCAMLMAKEFILE = ../OCamlMakefile

ANNOTATE = yes
SOURCES = sql_backend.ml sql_init.ml sql_save.ml sql_get.ml sql_delete.ml
RESULT = orm
PACKS = sqlite3 type-of value
LIB_PACK_NAME = orm

LIBINSTALL_FILES = orm.cmx orm.cmxa orm.cma orm.cmi

.PHONY: all
all: ncl dcl
	@ :

include $(OCAMLMAKEFILE)
