OCAMLMAKEFILE = ../OCamlMakefile
ANNOTATE = yes

SOURCES = p4_weakid.ml pa_weakid.ml hweak.mli hweak.ml
PACKS = type-conv hash.syntax
RESULT = pa_weakid
USE_CAMLP4 = yes

.PHONY: all
all: dcl
	@ :

include $(OCAMLMAKEFILE)
