OCAMLMAKEFILE = ../OCamlMakefile
ANNOTATE = yes

SOURCES = ../hash/p4_hash.ml p4_weakid.ml pa_weakid.ml hweak.ml
PACKS = type-conv
RESULT = pa_weakid
USE_CAMLP4 = yes

.PHONY: all
all: dcl ncl
	@ :

include $(OCAMLMAKEFILE)
